# Mini Project - Analyze Student Marks Dataset

## Data Science with Python

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [4]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [5]:
df[["math score", "reading score", "writing score"]].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [6]:
df[["math score", "reading score", "writing score"]].max()

math score       100
reading score    100
writing score    100
dtype: int64

In [7]:
df[["math score", "reading score", "writing score"]].min()

math score        0
reading score    17
writing score    10
dtype: int64

In [8]:
results = pd.DataFrame({
    "Average": df[["math score", "reading score", "writing score"]].mean(),
    "Maximum": df[["math score", "reading score", "writing score"]].max(),
    "Minimum": df[["math score", "reading score", "writing score"]].min()
})

results

               Average  Maximum  Minimum
math score      66.089      100        0
reading score   69.169      100       17
writing score   68.054      100       10

## Conclusion

The Student Marks dataset contains 1000 student records.
There are no missing values in the dataset.
The average scores are highest in Reading, followed by Writing and Math.
All three subjects have a maximum score of 100.