# Week 1 - Practice Questions

## Python for Data Analysis

## Question 1 - Create a Pandas DataFrame Manually

In [5]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Arjun"],
    "Marks": [85, 92, 78]
}

df = pd.DataFrame(data)
df

    Name  Marks
0  Rahul     85
1  Priya     92
2  Arjun     78

## Question 2 - Handle Missing Values with fillna()

In [6]:
data = {
    "Name": ["Rahul", "Priya", "Arjun"],
    "Marks": [85, None, 78]
}

df = pd.DataFrame(data)

df = df.fillna(0)
df

    Name  Marks
0  Rahul   85.0
1  Priya    0.0
2  Arjun   78.0

## Question 3 - Sort DataFrame by a Column

In [7]:
data = {
    "Name": ["Rahul", "Priya", "Arjun"],
    "Marks": [85, 92, 78]
}

df = pd.DataFrame(data)

df.sort_values("Marks")

    Name  Marks
2  Arjun     78
0  Rahul     85
1  Priya     92

## Question 4 - Find Mean, Median and Mode

In [8]:
data = {
    "Math": [85, 92, 78, 85, 90],
    "Science": [88, 95, 80, 88, 92]
}

df = pd.DataFrame(data)

print("Mean:")
print(df.mean())

print("\nMedian:")
print(df.median())

print("\nMode:")
print(df.mode().iloc[0])

Mean:
Math       86.0
Science    88.6
dtype: float64

Median:
Math       85.0
Science    88.0
dtype: float64

Mode:
Math       85
Science    88
Name: 0, dtype: int64

## Conclusion

All Week 1 practice questions have been completed successfully.